--------------------------------------------------------
--  파일이 생성됨 - 수요일-5월-10-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD_INFO
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BOARD_INFO" 
   (	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"NO" NUMBER, 
	"CATEGORY" NUMBER, 
	"TITLE" VARCHAR2(150 BYTE), 
	"WRITER" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"STATUS" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."BOARD_INFO"."CREATE_DATE" IS '작성날짜';
   COMMENT ON COLUMN "SCOTT"."BOARD_INFO"."NO" IS '글번호';
   COMMENT ON COLUMN "SCOTT"."BOARD_INFO"."CATEGORY" IS '카테고리';
   COMMENT ON COLUMN "SCOTT"."BOARD_INFO"."TITLE" IS '글제목';
   COMMENT ON COLUMN "SCOTT"."BOARD_INFO"."WRITER" IS '작성자 아이디';
   COMMENT ON COLUMN "SCOTT"."BOARD_INFO"."NICKNAME" IS '작성자 닉네임';
   COMMENT ON COLUMN "SCOTT"."BOARD_INFO"."STATUS" IS '답변여부';
REM INSERTING into SCOTT.BOARD_INFO
SET DEFINE OFF;
Insert into SCOTT.BOARD_INFO (CREATE_DATE,NO,CATEGORY,TITLE,WRITER,NICKNAME,STATUS) values (to_date('23/05/10','RR/MM/DD'),4,1,'문의 등록 잘 되네요','testid','휴먼',0);
Insert into SCOTT.BOARD_INFO (CREATE_DATE,NO,CATEGORY,TITLE,WRITER,NICKNAME,STATUS) values (to_date('23/05/09','RR/MM/DD'),1,1,'첫번째 문의입니다','testid','휴먼',0);
Insert into SCOTT.BOARD_INFO (CREATE_DATE,NO,CATEGORY,TITLE,WRITER,NICKNAME,STATUS) values (to_date('23/05/09','RR/MM/DD'),2,1,'두번째 문의입니다','testid','휴먼',0);
Insert into SCOTT.BOARD_INFO (CREATE_DATE,NO,CATEGORY,TITLE,WRITER,NICKNAME,STATUS) values (to_date('23/05/10','RR/MM/DD'),3,1,'문의문의 나문희','testid','휴먼',0);
--------------------------------------------------------
--  DDL for Index BOARD_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BOARD_INFO_PK" ON "SCOTT"."BOARD_INFO" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  Constraints for Table BOARD_INFO
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD_INFO" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD_INFO" MODIFY ("NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD_INFO" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD_INFO" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD_INFO" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD_INFO" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD_INFO" ADD CONSTRAINT "BOARD_INFO_PK" PRIMARY KEY ("NO")
  USING INDEX "SCOTT"."BOARD_INFO_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_INFO
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD_INFO" ADD CONSTRAINT "BOARD_INFO_FK1" FOREIGN KEY ("WRITER")
	  REFERENCES "SCOTT"."MEMBER_TB" ("LOGIN_ID") ENABLE;
