--------------------------------------------------------
--  파일이 생성됨 - 일요일-5월-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------
--SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

  CREATE TABLE "SCOTT"."BOARD" 
   (	"BOARD_NO" NUMBER, 
	"POST_NO" NUMBER, 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"MODIFY_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."BOARD"."BOARD_NO" IS '게시판번호';
   COMMENT ON COLUMN "SCOTT"."BOARD"."POST_NO" IS '게시글번호';
   COMMENT ON COLUMN "SCOTT"."BOARD"."LOGIN_ID" IS '외래키/아이디(작성자)';
   COMMENT ON COLUMN "SCOTT"."BOARD"."TITLE" IS '글제목';
   COMMENT ON COLUMN "SCOTT"."BOARD"."CREATE_DATE" IS '생성날짜';
   COMMENT ON COLUMN "SCOTT"."BOARD"."MODIFY_DATE" IS '수정날짜';
   COMMENT ON COLUMN "SCOTT"."BOARD"."STATUS" IS '답변상태';
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CART" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"REGISTER_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."CART"."LOGIN_ID" IS '외래키/소유자';
   COMMENT ON COLUMN "SCOTT"."CART"."REGISTER_NO" IS '외래키/상품번호';
--------------------------------------------------------
--  DDL for Table GIFTICON
--------------------------------------------------------

  CREATE TABLE "SCOTT"."GIFTICON" 
   (	"REGISTER_NO" NUMBER, 
	"BRAND_CODE" VARCHAR2(30 BYTE), 
	"BRAND_NAME" VARCHAR2(100 BYTE), 
	"COUPON_NUMBER" VARCHAR2(30 BYTE), 
	"COUPON_NAME" VARCHAR2(200 BYTE), 
	"PURCHASE_PRICE" NUMBER, 
	"SALE_PRICE" NUMBER, 
	"ORIGIN_PRICE" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"LOGIN_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."GIFTICON"."REGISTER_NO" IS '쿠폰등록번호';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."BRAND_CODE" IS '브랜드코드';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."BRAND_NAME" IS '브랜드이름';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."COUPON_NUMBER" IS '쿠폰번호(고유)';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."COUPON_NAME" IS '쿠폰이름';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."PURCHASE_PRICE" IS '매입가격';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."SALE_PRICE" IS '판매가격';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."ORIGIN_PRICE" IS '쿠폰정가';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."START_DATE" IS '발급날짜';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."END_DATE" IS '만료날짜';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."LOGIN_ID" IS '외래키/소유자';
--------------------------------------------------------
--  DDL for Table IMAGE_FILE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."IMAGE_FILE" 
   (	"FILE_NO" NUMBER, 
	"FILE_NAME" VARCHAR2(500 BYTE), 
	"BANNER_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."IMAGE_FILE"."FILE_NO" IS '파일고유번호';
   COMMENT ON COLUMN "SCOTT"."IMAGE_FILE"."FILE_NAME" IS '파일이름';
   COMMENT ON COLUMN "SCOTT"."IMAGE_FILE"."BANNER_NO" IS '배너등록번호';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MEMBER" 
   (	"MEMBER_NO" NUMBER, 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"JOIN_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."MEMBER"."MEMBER_NO" IS '회원번호';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."LOGIN_ID" IS '로그인 아이디';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."PASSWORD" IS '로그인 비밀번호';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."MEMBER_NAME" IS '회원이름';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."NICKNAME" IS '닉네임';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."JOIN_DATE" IS '가입날짜';
--------------------------------------------------------
--  DDL for Table POINT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."POINT" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"POINT" NUMBER DEFAULT 0, 
	"WITHDRAW" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."POINT"."LOGIN_ID" IS '외래키/소유자';
   COMMENT ON COLUMN "SCOTT"."POINT"."POINT" IS '잔여포인트';
   COMMENT ON COLUMN "SCOTT"."POINT"."WITHDRAW" IS '출금대기';
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "SCOTT"."POST" 
   (	"BOARD_NO" NUMBER(20,0), 
	"POST_NO" NUMBER(20,0), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"ANSWER" VARCHAR2(1000 BYTE), 
	"ANSWER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."POST"."BOARD_NO" IS '외래키/게시판번호(공지/문의)';
   COMMENT ON COLUMN "SCOTT"."POST"."POST_NO" IS '외래키/게시글번호';
   COMMENT ON COLUMN "SCOTT"."POST"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "SCOTT"."POST"."ANSWER" IS '답변내용';
   COMMENT ON COLUMN "SCOTT"."POST"."ANSWER_DATE" IS '답변날짜';
--------------------------------------------------------
--  DDL for Table SHOPPING_HISTORY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SHOPPING_HISTORY" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"REGISTER_NO" NUMBER, 
	"HISTORY_DATE" DATE DEFAULT SYSDATE, 
	"TYPE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."SHOPPING_HISTORY"."LOGIN_ID" IS '외래키/아이디';
   COMMENT ON COLUMN "SCOTT"."SHOPPING_HISTORY"."REGISTER_NO" IS '외래키/상품번호';
   COMMENT ON COLUMN "SCOTT"."SHOPPING_HISTORY"."HISTORY_DATE" IS '기록날짜';
   COMMENT ON COLUMN "SCOTT"."SHOPPING_HISTORY"."TYPE" IS '거래유형';
--------------------------------------------------------
--  DDL for Table TRANSACTION_HISTORY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TRANSACTION_HISTORY" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"HISTORY_DATE" DATE DEFAULT SYSDATE, 
	"AMOUNT" NUMBER, 
	"TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."TRANSACTION_HISTORY"."LOGIN_ID" IS '외래키/소유자';
   COMMENT ON COLUMN "SCOTT"."TRANSACTION_HISTORY"."HISTORY_DATE" IS '기록날짜';
   COMMENT ON COLUMN "SCOTT"."TRANSACTION_HISTORY"."AMOUNT" IS '입금액';
   COMMENT ON COLUMN "SCOTT"."TRANSACTION_HISTORY"."TYPE" IS '거래타입';
REM INSERTING into SCOTT.BOARD
SET DEFINE OFF;
Insert into SCOTT.BOARD (BOARD_NO,POST_NO,LOGIN_ID,TITLE,CREATE_DATE,MODIFY_DATE,STATUS) values (1,1,'chlgmlen','구매한 상품들을 찾을 수가 없어요.',to_date('23/05/21','RR/MM/DD'),to_date('23/05/21','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NO,POST_NO,LOGIN_ID,TITLE,CREATE_DATE,MODIFY_DATE,STATUS) values (1,2,'test','출금 신청했는데 언제 승인 해주시나요?',to_date('23/05/21','RR/MM/DD'),to_date('23/05/21','RR/MM/DD'),0);
Insert into SCOTT.BOARD (BOARD_NO,POST_NO,LOGIN_ID,TITLE,CREATE_DATE,MODIFY_DATE,STATUS) values (1,3,'chlgmlen','스타벅스 기프티콘 구매도 가능한가요?',to_date('23/05/21','RR/MM/DD'),to_date('23/05/21','RR/MM/DD'),0);
REM INSERTING into SCOTT.CART
SET DEFINE OFF;
REM INSERTING into SCOTT.GIFTICON
SET DEFINE OFF;
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (1,'BRTEST','배스킨라빈스','5125468','MSGR 블라스트',5100,5100,5100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (2,'BRTEST','배스킨라빈스','4267578','골라 먹는 27 큐브(배달가능)',8100,8100,8100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (3,'BRTEST','배스킨라빈스','3658410','골라 먹는 와츄원(배달가능)',12200,12200,12200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (4,'BRTEST','배스킨라빈스','3894241','기라델리 초코마블 블라스트',13500,13500,13500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (5,'BRTEST','배스킨라빈스','3447000','나눠먹는 와츄원(배달가능)',9900,9900,9900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (6,'BRTEST','배스킨라빈스','1120558','나눠먹는 큐브 와츄원(배달가능)',10600,10600,10600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (7,'BRTEST','배스킨라빈스','7933682','납작복숭아 요거트 블라스트',7800,7800,7800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (8,'BRTEST','배스킨라빈스','1798486','닉 스틱바 망고',20000,20000,20000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (9,'BRTEST','배스킨라빈스','9200509','더블레귤러 아이스크림',18500,18500,18500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (10,'BRTEST','배스킨라빈스','5301365','더블주니어 아이스크림',8000,8000,8000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (11,'BRTEST','배스킨라빈스','4898558','더블쿠키샌드 바닐라&초콜릿',1400,1400,1400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (12,'BRTEST','배스킨라빈스','8981908','도날드 덕 스틱바 소다',3000,3000,3000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (13,'BRTEST','배스킨라빈스','2415073','돌하르방 아이스 모나카 우도 땅콩&바닐라',17000,17000,17000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (14,'BRTEST','배스킨라빈스','7099529','돌하르방 아이스 모나카 제주그린티&팥',16600,16600,16600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (15,'BRTEST','배스킨라빈스','7310495','디카페인 마끼아또 (HOT)',17100,17100,17100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (16,'BRTEST','배스킨라빈스','9944519','디카페인 마끼아또 (ICED)',2600,2600,2600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (17,'BRTEST','배스킨라빈스','4770852','디카페인 바닐라빈 라떼 (HOT)',8700,8700,8700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (18,'BRTEST','배스킨라빈스','4817675','디카페인 바닐라빈 라떼 (ICED)',17400,17400,17400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (19,'BRTEST','배스킨라빈스','9280957','디카페인 아메리카노 (HOT)',14000,14000,14000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (20,'BRTEST','배스킨라빈스','6421553','디카페인 아메리카노 (ICED)',20000,20000,20000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (21,'BRTEST','배스킨라빈스','4721607','디카페인 아메리카노 Large (HOT)',19800,19800,19800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (22,'BRTEST','배스킨라빈스','3140158','디카페인 아메리카노 Large (ICED)',15100,15100,15100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (23,'BRTEST','배스킨라빈스','576664','디카페인 연유라떼 (HOT)',8700,8700,8700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (24,'BRTEST','배스킨라빈스','7090460','디카페인 연유라떼 (ICED)',16200,16200,16200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (25,'BRTEST','배스킨라빈스','8507106','디카페인 카페라떼 (HOT)',2600,2600,2600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (26,'BRTEST','배스킨라빈스','8090842','디카페인 카페라떼 (ICED)',7100,7100,7100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (27,'BRTEST','배스킨라빈스','968613','딸기 연유라떼',5500,5500,5500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (28,'BRTEST','배스킨라빈스','4583745','딸기 치즈케이크 블라스트',3400,3400,3400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (29,'BRTEST','배스킨라빈스','1232998','랏소 베어 스틱바 파인애플',14800,14800,14800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (30,'BRTEST','배스킨라빈스','1754145','레디팩 2개',10600,10600,10600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (31,'BRTEST','배스킨라빈스','3694112','레디팩(474ml) 1개 (플레이버 택1)',10400,10400,10400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (32,'BRTEST','배스킨라빈스','8689781','마이멜로디 스틱바 복숭아',11000,11000,11000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (33,'BRTEST','배스킨라빈스','8924194','마이멜로디의 인형뽑기(배달가능)',16200,16200,16200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (34,'BRTEST','배스킨라빈스','1427629','맥심 스틱바 모카골드 마일드',3400,3400,3400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (35,'BRTEST','배스킨라빈스','8981847','맥심 스틱바 화이트골드',10600,10600,10600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (36,'BRTEST','배스킨라빈스','7524140','모바일 금액권 1만원권',16200,16200,16200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (37,'BRTEST','배스킨라빈스','1998863','모바일 금액권 3만원권',7300,7300,7300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (38,'BRTEST','배스킨라빈스','4681044','모바일 금액권 5만원권',16900,16900,16900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (39,'BRTEST','배스킨라빈스','8287251','모바일 금액권 10만원권',9400,9400,9400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (40,'BRTEST','배스킨라빈스','1666866','미니 골라 먹는 와츄원(배달가능)',12200,12200,12200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (41,'BRTEST','배스킨라빈스','2963620','미니 레디팩(260ml) 1개 (플레이버 택1)',18700,18700,18700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (42,'BRTEST','배스킨라빈스','3915891','미니 아이스 모찌 (3종)',9200,9200,9200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (43,'BRTEST','배스킨라빈스','7395223','미니 아이스 스틱바 바닐라(3개입)',19700,19700,19700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (44,'BRTEST','배스킨라빈스','9786490','미니 해피버스데이 케이크(배달가능)',4200,4200,4200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (46,'BRTEST','배스킨라빈스','1451194','밀크 쉐이크 (Regular)',12700,12700,12700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (47,'BRTEST','배스킨라빈스','1869508','바닐라빈 라떼 (HOT)',8900,8900,8900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (48,'BRTEST','배스킨라빈스','8109502','바닐라빈 라떼 (ICED)',7500,7500,7500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (49,'BRTEST','배스킨라빈스','6463073','바삭바삭 비스코프 케이크',17300,17300,17300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (50,'BRTEST','배스킨라빈스','8905304','버라이어티팩(배달가능)',15500,15500,15500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (51,'BRTEST','배스킨라빈스','1462811','베이비 멜론 타르트(배달가능)',8500,8500,8500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (52,'BRTEST','배스킨라빈스','244368','베이비 애플 타르트(배달가능)',2400,2400,2400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (53,'BRTEST','배스킨라빈스','801152','베이비 피치 타르트(배달가능)',14500,14500,14500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (54,'BRTEST','배스킨라빈스','2700248','블랙 소르베 싱글킹 아이스크림',8000,8000,8000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (55,'BRTEST','배스킨라빈스','1048979','블록팩 (110ml) 1개 (10종 중 택1)',4600,4600,4600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (56,'BRTEST','배스킨라빈스','8332084','블록팩 (110ml) 4개 SET',6600,6600,6600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (57,'BRTEST','배스킨라빈스','7614912','블록팩 (110ml) 6개 SET',13400,13400,13400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (58,'BRTEST','배스킨라빈스','884198','사과나라 헬로키티 싱글킹 아이스크림',1200,1200,1200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (59,'BRTEST','배스킨라빈스','4398370','설향 딸기 블라스트',9600,9600,9600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (60,'BRTEST','배스킨라빈스','1270634','소금우유 아이스 모찌',19300,19300,19300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (62,'BRTEST','배스킨라빈스','5149347','솔티크림라떼(ICED)',13000,13000,13000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (63,'BRTEST','배스킨라빈스','3689767','솔티크림슈페너(HOT)',10500,10500,10500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (64,'BRTEST','배스킨라빈스','848621','솔티크림슈페너(ICED)',4100,4100,4100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (65,'BRTEST','배스킨라빈스','5015112','스틱커피 (10개입)',8000,8000,8000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (66,'BRTEST','배스킨라빈스','5916582','시나모롤 말랑말랑 구름찰떡',9500,9500,9500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (67,'BRTEST','배스킨라빈스','2036987','시나모롤 소다 블라스트',2200,2200,2200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (68,'BRTEST','배스킨라빈스','2023734','싱글레귤러 아이스크림',2100,2100,2100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (69,'BRTEST','배스킨라빈스','5333224','싱글킹 아이스크림',16800,16800,16800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (70,'BRTEST','배스킨라빈스','7664997','아메리카노 (HOT)',6200,6200,6200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (71,'BRTEST','배스킨라빈스','8505575','아메리카노 (ICED)',17000,17000,17000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (72,'BRTEST','배스킨라빈스','9294586','아메리카노 Large (HOT)',13700,13700,13700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (45,'BRTEST','배스킨라빈스','6296534','미키 마우스 스틱바 블랙 소르베',1900,1900,1900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (61,'BRTEST','배스킨라빈스','6232943','솔티크림라떼(HOT)',13300,13300,13300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (73,'BRTEST','배스킨라빈스','4404228','아메리카노 Large (ICED)',2100,2100,2100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (74,'BRTEST','배스킨라빈스','6303410','아몬드 봉봉 블라스트 (Regular)',10100,10100,10100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (75,'BRTEST','배스킨라빈스','5104761','아몬드 봉봉 초코라떼(HOT)',3300,3300,3300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (76,'BRTEST','배스킨라빈스','7139877','아몬드 봉봉 초코라떼(ICED)',7900,7900,7900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (77,'BRTEST','배스킨라빈스','7520709','아빵 우유',7300,7300,7300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (78,'BRTEST','배스킨라빈스','312737','아이스 기라델리 초콜릿 볼',9900,9900,9900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (79,'BRTEST','배스킨라빈스','3062111','아이스 기라델리 초콜릿 타르트',4900,4900,4900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (80,'BRTEST','배스킨라빈스','8836690','아이스 마카롱 체리쥬빌레',5000,5000,5000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (81,'BRTEST','배스킨라빈스','701930','아이스 마카롱 초콜릿 무스',11900,11900,11900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (82,'BRTEST','배스킨라빈스','2632148','아이스 마카롱 치즈',5200,5200,5200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (83,'BRTEST','배스킨라빈스','1323071','아이스 마카롱 쿠키앤크림',12500,12500,12500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (84,'BRTEST','배스킨라빈스','4620161','아이스 모나카 우유',3600,3600,3600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (85,'BRTEST','배스킨라빈스','8079673','아이스 모찌 (그린티)',17000,17000,17000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (86,'BRTEST','배스킨라빈스','818633','아이스 모찌 (바나나킥)',7500,7500,7500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (87,'BRTEST','배스킨라빈스','3664870','아이스 모찌 (스트로베리)',11100,11100,11100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (88,'BRTEST','배스킨라빈스','7109621','아이스 모찌 (초코바닐라)',11100,11100,11100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (89,'BRTEST','배스킨라빈스','4436690','아이스 모찌 (크림치즈)',8700,8700,8700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (90,'BRTEST','배스킨라빈스','8878713','아이스 모찌 망고',17900,17900,17900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (92,'BRTEST','배스킨라빈스','9201707','아이스 쿠키 샌드 바닐라',4400,4400,4400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (93,'BRTEST','배스킨라빈스','2231543','아이스 호떡 (모찌)',6700,6700,6700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (94,'BRTEST','배스킨라빈스','5352671','아이스크림 롤 (초콜릿)',12700,12700,12700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (95,'BRTEST','배스킨라빈스','3108854','아이스크림 스틱바 (민트쿠앤크)',9000,9000,9000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (96,'BRTEST','배스킨라빈스','7218841','아이스크림 스틱바 (초코그린티)',15700,15700,15700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (97,'BRTEST','배스킨라빈스','4172164','아포가토 라떼(ICED)',18100,18100,18100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (98,'BRTEST','배스킨라빈스','8725843','알고보면 스윗한 쿠로미(배달가능)',4300,4300,4300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (99,'BRTEST','배스킨라빈스','853537','알린 스틱바 그린애플',18200,18200,18200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (100,'BRTEST','배스킨라빈스','1861','엄마는 외계인 블라스트 (Regular)',9500,9500,9500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (101,'BRTEST','배스킨라빈스','6941468','엄마는 외계인 초코라떼 (ICED)',19300,19300,19300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (102,'BRTEST','배스킨라빈스','3048118','엄마는 외계인 카페모카 (ICED)',14300,14300,14300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (103,'BRTEST','배스킨라빈스','4766788','연유라떼 (HOT)',17300,17300,17300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (104,'BRTEST','배스킨라빈스','2848465','연유라떼 (ICED)',10700,10700,10700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (105,'BRTEST','배스킨라빈스','9031847','오레오 딸기 쉐이크 (Regular)',6300,6300,6300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (106,'BRTEST','배스킨라빈스','3761960','오레오 쉐이크 (Regular)',6700,6700,6700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (107,'BRTEST','배스킨라빈스','3238896','오레오 초코 쉐이크 (Regular)',2100,2100,2100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (108,'BRTEST','배스킨라빈스','3724539','옹기종기팩(배달가능)',6100,6100,6100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (109,'BRTEST','배스킨라빈스','5811445','와츄원 쉐이크 (Regular)',10300,10300,10300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (110,'BRTEST','배스킨라빈스','6170901','외계인의 바나나킥 블라스트',17700,17700,17700,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (111,'BRTEST','배스킨라빈스','3992412','우아한 백조 케이크(배달가능)',15300,15300,15300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (112,'BRTEST','배스킨라빈스','8013323','위글위글 허니비(배달가능)',14400,14400,14400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (113,'BRTEST','배스킨라빈스','7923553','유자 요거트 블라스트',13800,13800,13800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (114,'BRTEST','배스킨라빈스','6724583','유자 캐모마일 티(HOT)',2000,2000,2000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (115,'BRTEST','배스킨라빈스','596908','유자 캐모마일 티(ICED)',16800,16800,16800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (116,'BRTEST','배스킨라빈스','7217756','제주 감귤 아이스 모찌',8200,8200,8200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (117,'BRTEST','배스킨라빈스','4911551','주디 스틱바 스트로베리',18100,18100,18100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (118,'BRTEST','배스킨라빈스','353080','초코마시멜로 아이스 초코파이',18000,18000,18000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (119,'BRTEST','배스킨라빈스','315382','카라멜 마끼아또 (HOT)',12600,12600,12600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (120,'BRTEST','배스킨라빈스','6494236','카라멜 마끼아또 (ICED)',10200,10200,10200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (121,'BRTEST','배스킨라빈스','4565289','카페31 아이스 아메리카노',17900,17900,17900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (122,'BRTEST','배스킨라빈스','5452370','카페라떼 (HOT)',10900,10900,10900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (123,'BRTEST','배스킨라빈스','2259650','카페라떼 (ICED)',18000,18000,18000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (124,'BRTEST','배스킨라빈스','5671423','카페브리즈 커피빈(250g)',6900,6900,6900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (125,'BRTEST','배스킨라빈스','9900843','카푸치노블라스트 모카 (Regular)',8100,8100,8100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (126,'BRTEST','배스킨라빈스','1804463','카푸치노블라스트 오리지널 (Regular)',7900,7900,7900,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (127,'BRTEST','배스킨라빈스','6404377','캐릭터 토이컵 (3종 중 택1)',3600,3600,3600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (128,'BRTEST','배스킨라빈스','8495593','콜드브루 오트',1100,1100,1100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (129,'BRTEST','배스킨라빈스','9914081','쿠로미 스틱바 포도',16000,16000,16000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (130,'BRTEST','배스킨라빈스','5709830','쿼터 아이스크림(배달가능)',9300,9300,9300,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (131,'BRTEST','배스킨라빈스','3394104','파인트 아이스크림(배달가능)',14200,14200,14200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (132,'BRTEST','배스킨라빈스','5244462','팝핑보바 리치베리 티',2800,2800,2800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (133,'BRTEST','배스킨라빈스','7289502','팝핑보바 청포도 블라스트',1800,1800,1800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (134,'BRTEST','배스킨라빈스','916436','팝핑보바 핑크파인 블라스트',16500,16500,16500,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (135,'BRTEST','배스킨라빈스','2274943','패밀리 아이스크림(배달가능)',6200,6200,6200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (136,'BRTEST','배스킨라빈스','4564268','페코의 스트로베리 푸딩(배달가능)',5600,5600,5600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (137,'BRTEST','배스킨라빈스','6099320','플레인 요거트 블라스트',7400,7400,7400,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (138,'BRTEST','배스킨라빈스','3548785','하프갤론 아이스크림(배달가능)',2800,2800,2800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (139,'BRTEST','배스킨라빈스','8292349','해피버스데이(배달가능)',18600,18600,18600,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (140,'BRTEST','배스킨라빈스','1410304','핸드팩세트 (파인트 4개)(배달가능)',14100,14100,14100,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (141,'BRTEST','배스킨라빈스','5193773','흑임자 오트(HOT)',17200,17200,17200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (142,'BRTEST','배스킨라빈스','4172073','흑임자 오트(ICED)',1000,1000,1000,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (143,'BRTEST','배스킨라빈스','5718659','흑임자 크림치즈 블라스트',4800,4800,4800,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (144,'BRTEST','배스킨라빈스','9308970','복숭아 아이스티',17200,17200,17200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
Insert into SCOTT.GIFTICON (REGISTER_NO,BRAND_CODE,BRAND_NAME,COUPON_NUMBER,COUPON_NAME,PURCHASE_PRICE,SALE_PRICE,ORIGIN_PRICE,START_DATE,END_DATE,LOGIN_ID) values (91,'BRTEST','배스킨라빈스','2074012','아이스 초코파이 민트초코칩',19200,19200,19200,to_date('23/05/17','RR/MM/DD'),to_date('23/05/20','RR/MM/DD'),null);
REM INSERTING into SCOTT.IMAGE_FILE
SET DEFINE OFF;
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (2,'MSGR 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (3,'골라 먹는 27 큐브(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (4,'골라 먹는 와츄원(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (5,'기라델리 초코마블 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (6,'나눠먹는 와츄원(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (7,'나눠먹는 큐브 와츄원(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (8,'납작복숭아 요거트 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (9,'닉 스틱바 망고.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (10,'더블레귤러 아이스크림.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (11,'더블주니어 아이스크림.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (12,'더블쿠키샌드 바닐라&초콜릿.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (13,'도날드 덕 스틱바 소다.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (14,'돌하르방 아이스 모나카 우도 땅콩&바닐라.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (15,'돌하르방 아이스 모나카 제주그린티&팥.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (16,'디카페인 마끼아또 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (17,'디카페인 마끼아또 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (18,'디카페인 바닐라빈 라떼 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (19,'디카페인 바닐라빈 라떼 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (20,'디카페인 아메리카노 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (21,'디카페인 아메리카노 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (22,'디카페인 아메리카노 Large (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (23,'디카페인 아메리카노 Large (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (24,'디카페인 연유라떼 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (25,'디카페인 연유라떼 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (26,'디카페인 카페라떼 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (27,'디카페인 카페라떼 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (28,'딸기 연유라떼.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (29,'딸기 치즈케이크 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (30,'랏소 베어 스틱바 파인애플.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (31,'레디팩 2개.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (32,'레디팩(474ml) 1개 (플레이버 택1).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (33,'마이멜로디 스틱바 복숭아.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (34,'마이멜로디의 인형뽑기(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (35,'맥심 스틱바 모카골드 마일드.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (36,'맥심 스틱바 화이트골드.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (37,'모바일 금액권 1만원권.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (38,'모바일 금액권 3만원권.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (39,'모바일 금액권 5만원권.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (40,'모바일 금액권 10만원권.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (41,'미니 골라 먹는 와츄원(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (42,'미니 레디팩(260ml) 1개 (플레이버 택1).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (43,'미니 아이스 모찌 (3종).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (44,'미니 아이스 스틱바 바닐라(3개입).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (45,'미니 해피버스데이 케이크(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (46,'미키 마우스 스틱바 블랙 소르베.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (47,'밀크 쉐이크 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (48,'바닐라빈 라떼 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (49,'바닐라빈 라떼 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (50,'바삭바삭 비스코프 케이크.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (51,'버라이어티팩(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (52,'베이비 멜론 타르트(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (53,'베이비 애플 타르트(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (54,'베이비 피치 타르트(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (55,'블랙 소르베 싱글킹 아이스크림.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (56,'블록팩 (110ml) 1개 (10종 중 택1).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (57,'블록팩 (110ml) 4개 SET.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (58,'블록팩 (110ml) 6개 SET.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (59,'사과나라 헬로키티 싱글킹 아이스크림.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (60,'설향 딸기 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (61,'소금우유 아이스 모찌.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (62,'솔티크림라떼(HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (63,'솔티크림라떼(ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (64,'솔티크림슈페너(HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (65,'솔티크림슈페너(ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (66,'스틱커피 (10개입).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (67,'시나모롤 말랑말랑 구름찰떡.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (68,'시나모롤 소다 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (69,'싱글레귤러 아이스크림.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (70,'싱글킹 아이스크림.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (71,'아메리카노 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (72,'아메리카노 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (73,'아메리카노 Large (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (74,'아메리카노 Large (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (75,'아몬드 봉봉 블라스트 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (76,'아몬드 봉봉 초코라떼(HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (77,'아몬드 봉봉 초코라떼(ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (78,'아빵 우유.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (79,'아이스 기라델리 초콜릿 볼.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (80,'아이스 기라델리 초콜릿 타르트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (81,'아이스 마카롱 체리쥬빌레.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (82,'아이스 마카롱 초콜릿 무스.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (83,'아이스 마카롱 치즈.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (84,'아이스 마카롱 쿠키앤크림.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (85,'아이스 모나카 우유.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (86,'아이스 모찌 (그린티).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (87,'아이스 모찌 (바나나킥).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (88,'아이스 모찌 (스트로베리).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (89,'아이스 모찌 (초코바닐라).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (90,'아이스 모찌 (크림치즈).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (91,'아이스 모찌 망고.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (92,'아이스 초코파이 민트초코칩.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (93,'아이스 쿠키 샌드 바닐라.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (94,'아이스 호떡 (모찌).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (95,'아이스크림 롤 (초콜릿).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (96,'아이스크림 스틱바 (민트쿠앤크).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (97,'아이스크림 스틱바 (초코그린티).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (98,'아포가토 라떼(ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (99,'알고보면 스윗한 쿠로미(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (100,'알린 스틱바 그린애플.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (101,'엄마는 외계인 블라스트 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (102,'엄마는 외계인 초코라떼 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (103,'엄마는 외계인 카페모카 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (104,'연유라떼 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (105,'연유라떼 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (106,'오레오 딸기 쉐이크 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (107,'오레오 쉐이크 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (108,'오레오 초코 쉐이크 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (109,'옹기종기팩(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (110,'와츄원 쉐이크 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (111,'외계인의 바나나킥 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (112,'우아한 백조 케이크(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (113,'위글위글 허니비(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (114,'유자 요거트 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (115,'유자 캐모마일 티(HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (116,'유자 캐모마일 티(ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (117,'제주 감귤 아이스 모찌.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (118,'주디 스틱바 스트로베리.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (119,'초코마시멜로 아이스 초코파이.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (120,'카라멜 마끼아또 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (121,'카라멜 마끼아또 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (122,'카페31 아이스 아메리카노.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (123,'카페라떼 (HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (124,'카페라떼 (ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (125,'카페브리즈 커피빈(250g).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (126,'카푸치노블라스트 모카 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (127,'카푸치노블라스트 오리지널 (Regular).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (128,'캐릭터 토이컵 (3종 중 택1).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (129,'콜드브루 오트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (130,'쿠로미 스틱바 포도.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (131,'쿼터 아이스크림(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (132,'파인트 아이스크림(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (133,'팝핑보바 리치베리 티.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (134,'팝핑보바 청포도 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (135,'팝핑보바 핑크파인 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (136,'패밀리 아이스크림(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (137,'페코의 스트로베리 푸딩(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (138,'플레인 요거트 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (139,'하프갤론 아이스크림(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (140,'해피버스데이(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (141,'핸드팩세트 (파인트 4개)(배달가능).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (142,'흑임자 오트(HOT).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (143,'흑임자 오트(ICED).png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (144,'흑임자 크림치즈 블라스트.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (1,'복숭아 아이스티.png',null);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (145,'evt11.png',1);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (146,'evt21.png',2);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (147,'evt31.png',3);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (148,'evt41.png',4);
Insert into SCOTT.IMAGE_FILE (FILE_NO,FILE_NAME,BANNER_NO) values (149,'evt51.png',5);
REM INSERTING into SCOTT.MEMBER
SET DEFINE OFF;
Insert into SCOTT.MEMBER (MEMBER_NO,LOGIN_ID,PASSWORD,MEMBER_NAME,NICKNAME,JOIN_DATE) values (2,'test','1234','이의성','마늘',to_date('23/05/15','RR/MM/DD'));
Insert into SCOTT.MEMBER (MEMBER_NO,LOGIN_ID,PASSWORD,MEMBER_NAME,NICKNAME,JOIN_DATE) values (1,'admin','admin','admin','관리자',to_date('23/05/14','RR/MM/DD'));
Insert into SCOTT.MEMBER (MEMBER_NO,LOGIN_ID,PASSWORD,MEMBER_NAME,NICKNAME,JOIN_DATE) values (3,'chlgmlen','chlgmlen','최희두','최희두',to_date('23/05/21','RR/MM/DD'));
REM INSERTING into SCOTT.POINT
SET DEFINE OFF;
Insert into SCOTT.POINT (LOGIN_ID,POINT,WITHDRAW) values ('test',0,0);
Insert into SCOTT.POINT (LOGIN_ID,POINT,WITHDRAW) values ('admin',46500,0);
Insert into SCOTT.POINT (LOGIN_ID,POINT,WITHDRAW) values ('chlgmlen',248200,160000);
REM INSERTING into SCOTT.POST
SET DEFINE OFF;
Insert into SCOTT.POST (BOARD_NO,POST_NO,CONTENT,ANSWER,ANSWER_DATE) values (1,1,'안녕하세요. 

고생 많으십니다.

어느 페이지로 가야 구매상품들을 볼 수 있을까요?',null,null);
Insert into SCOTT.POST (BOARD_NO,POST_NO,CONTENT,ANSWER,ANSWER_DATE) values (1,2,'제가 돈이 급한데 빨리 처리좀 부탁드립니다.',null,null);
Insert into SCOTT.POST (BOARD_NO,POST_NO,CONTENT,ANSWER,ANSWER_DATE) values (1,3,'스타벅스 커피가 마시고 싶어요!',null,null);
REM INSERTING into SCOTT.SHOPPING_HISTORY
SET DEFINE OFF;
REM INSERTING into SCOTT.TRANSACTION_HISTORY
SET DEFINE OFF;
Insert into SCOTT.TRANSACTION_HISTORY (LOGIN_ID,HISTORY_DATE,AMOUNT,TYPE) values ('test',to_date('23/05/15','RR/MM/DD'),50000,1);
Insert into SCOTT.TRANSACTION_HISTORY (LOGIN_ID,HISTORY_DATE,AMOUNT,TYPE) values ('test',to_date('23/05/15','RR/MM/DD'),50000,1);
Insert into SCOTT.TRANSACTION_HISTORY (LOGIN_ID,HISTORY_DATE,AMOUNT,TYPE) values ('chlgmlen',to_date('23/05/21','RR/MM/DD'),100000,1);
Insert into SCOTT.TRANSACTION_HISTORY (LOGIN_ID,HISTORY_DATE,AMOUNT,TYPE) values ('chlgmlen',to_date('23/05/21','RR/MM/DD'),10000,1);
Insert into SCOTT.TRANSACTION_HISTORY (LOGIN_ID,HISTORY_DATE,AMOUNT,TYPE) values ('chlgmlen',to_date('23/05/21','RR/MM/DD'),500000,1);
Insert into SCOTT.TRANSACTION_HISTORY (LOGIN_ID,HISTORY_DATE,AMOUNT,TYPE) values ('admin',to_date('23/05/21','RR/MM/DD'),50000,1);
Insert into SCOTT.TRANSACTION_HISTORY (LOGIN_ID,HISTORY_DATE,AMOUNT,TYPE) values ('test',to_date('23/05/21','RR/MM/DD'),8000000,1);
--------------------------------------------------------
--  DDL for Index BORAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BORAD_PK" ON "SCOTT"."BOARD" ("BOARD_NO", "POST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index GIFTICON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."GIFTICON_PK" ON "SCOTT"."GIFTICON" ("REGISTER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index GIFTICON_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."GIFTICON_UK1" ON "SCOTT"."GIFTICON" ("COUPON_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index IMAGE_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."IMAGE_FILE_PK" ON "SCOTT"."IMAGE_FILE" ("FILE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."MEMBER_PK" ON "SCOTT"."MEMBER" ("LOGIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Procedure DELETE_BANNER
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SCOTT"."DELETE_BANNER" 
(
    param1 IN NUMBER
)
IS

BEGIN
DELETE image_file
WHERE banner_no = param1;

UPDATE image_file
SET banner_no = banner_no - 1
WHERE banner_no > param1;

END DELETE_BANNER;


/
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD" MODIFY ("BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("POST_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("MODIFY_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BOARD" ADD CONSTRAINT "BORAD_PK" PRIMARY KEY ("BOARD_NO", "POST_NO")
  USING INDEX "SCOTT"."BORAD_PK"  ENABLE;
  ALTER TABLE "SCOTT"."BOARD" MODIFY ("STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CART" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CART" MODIFY ("REGISTER_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GIFTICON
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("REGISTER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("BRAND_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("BRAND_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("COUPON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("COUPON_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("PURCHASE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("SALE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" ADD CONSTRAINT "GIFTICON_PK" PRIMARY KEY ("REGISTER_NO")
  USING INDEX "SCOTT"."GIFTICON_PK"  ENABLE;
  ALTER TABLE "SCOTT"."GIFTICON" ADD CONSTRAINT "GIFTICON_UK1" UNIQUE ("COUPON_NUMBER")
  USING INDEX "SCOTT"."GIFTICON_UK1"  ENABLE;
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("ORIGIN_PRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMAGE_FILE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."IMAGE_FILE" MODIFY ("FILE_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."IMAGE_FILE" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."IMAGE_FILE" ADD CONSTRAINT "IMAGE_FILE_PK" PRIMARY KEY ("FILE_NO")
  USING INDEX "SCOTT"."IMAGE_FILE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("LOGIN_ID")
  USING INDEX "SCOTT"."MEMBER_PK"  ENABLE;
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POINT" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POINT" MODIFY ("POINT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POINT" MODIFY ("WITHDRAW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POST" MODIFY ("BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POST" MODIFY ("POST_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POST" MODIFY ("CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOPPING_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" MODIFY ("REGISTER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" MODIFY ("HISTORY_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" MODIFY ("HISTORY_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BOARD" ADD CONSTRAINT "BORAD_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CART" ADD CONSTRAINT "CART_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GIFTICON
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GIFTICON" ADD CONSTRAINT "GIFTICON_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POINT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POINT" ADD CONSTRAINT "POINT_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POST" ADD CONSTRAINT "POST_FK1" FOREIGN KEY ("BOARD_NO", "POST_NO")
	  REFERENCES "SCOTT"."BOARD" ("BOARD_NO", "POST_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOPPING_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" ADD CONSTRAINT "BUYHISTORY_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" ADD CONSTRAINT "DISPOSITHISTORY_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ENABLE;
