--------------------------------------------------------
--  파일이 생성됨 - 금요일-5월-12-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BANNER_IMAGE
--------------------------------------------------------
--------------------------------------------------------
--전체 테이블 삭제하는 명령어 조회 후 복붙-실행으로 사용
--SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BANNER_IMAGE" 
   (	"BANNER_NO" NUMBER, 
	"FILE_PATH" VARCHAR2(100 BYTE), 
	"FILE_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."BANNER_IMAGE"."BANNER_NO" IS '배너번호';
   COMMENT ON COLUMN "SCOTT"."BANNER_IMAGE"."FILE_PATH" IS '외래키/파일경로';
   COMMENT ON COLUMN "SCOTT"."BANNER_IMAGE"."FILE_NAME" IS '외래키/파일명';
--------------------------------------------------------
--  DDL for Table BORAD
--------------------------------------------------------

  CREATE TABLE "SCOTT"."BORAD" 
   (	"BOARD_NO" NUMBER, 
	"POST_NO" NUMBER, 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"MODIFY_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."BORAD"."BOARD_NO" IS '게시판번호';
   COMMENT ON COLUMN "SCOTT"."BORAD"."POST_NO" IS '게시글번호';
   COMMENT ON COLUMN "SCOTT"."BORAD"."LOGIN_ID" IS '외래키/아이디(작성자)';
   COMMENT ON COLUMN "SCOTT"."BORAD"."TITLE" IS '글제목';
   COMMENT ON COLUMN "SCOTT"."BORAD"."CREATE_DATE" IS '생성날짜';
   COMMENT ON COLUMN "SCOTT"."BORAD"."MODIFY_DATE" IS '수정날짜';
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "SCOTT"."CART" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"REGISTER_NO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."CART"."LOGIN_ID" IS '외래키/소유자';
   COMMENT ON COLUMN "SCOTT"."CART"."REGISTER_NO" IS '외래키/상품번호';
--------------------------------------------------------
--  DDL for Table GIFTICON
--------------------------------------------------------

  CREATE TABLE "SCOTT"."GIFTICON" 
   (	"REGISTER_NO" NUMBER, 
	"BRAND_CODE" VARCHAR2(20 BYTE), 
	"BRAND_NAME" VARCHAR2(30 BYTE), 
	"COUPON_NUMBER" VARCHAR2(30 BYTE), 
	"COUPON_NAME" VARCHAR2(50 BYTE), 
	"PURCHASE_PRICE" NUMBER, 
	"SALE_PRICE" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"LOGIN_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."GIFTICON"."REGISTER_NO" IS '쿠폰등록번호';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."BRAND_CODE" IS '브랜드코드';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."BRAND_NAME" IS '브랜드이름';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."COUPON_NUMBER" IS '쿠폰번호(고유)';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."COUPON_NAME" IS '쿠폰이름';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."PURCHASE_PRICE" IS '매입가격';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."SALE_PRICE" IS '판매가격';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."START_DATE" IS '발급날짜';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."END_DATE" IS '만료날짜';
   COMMENT ON COLUMN "SCOTT"."GIFTICON"."LOGIN_ID" IS '외래키/소유자';
--------------------------------------------------------
--  DDL for Table GIFTICON_IMAGE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."GIFTICON_IMAGE" 
   (	"REGISTER_NO" NUMBER, 
	"FILE_PATH" VARCHAR2(100 BYTE), 
	"FILE_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."GIFTICON_IMAGE"."REGISTER_NO" IS '외래키/쿠폰등록번호';
   COMMENT ON COLUMN "SCOTT"."GIFTICON_IMAGE"."FILE_PATH" IS '외래키/파일경로';
   COMMENT ON COLUMN "SCOTT"."GIFTICON_IMAGE"."FILE_NAME" IS '외래키/파일명';
--------------------------------------------------------
--  DDL for Table IMAGE_FILE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."IMAGE_FILE" 
   (	"FILE_PATH" VARCHAR2(500 BYTE), 
	"FILE_NAME" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."IMAGE_FILE"."FILE_PATH" IS '파일경로';
   COMMENT ON COLUMN "SCOTT"."IMAGE_FILE"."FILE_NAME" IS '파일명';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MEMBER" 
   (	"MEMBER_NO" NUMBER, 
	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"JOIN_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."MEMBER"."MEMBER_NO" IS '회원번호';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."LOGIN_ID" IS '로그인 아이디';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."PASSWORD" IS '로그인 비밀번호';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."MEMBER_NAME" IS '회원이름';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."NICKNAME" IS '닉네임';
   COMMENT ON COLUMN "SCOTT"."MEMBER"."JOIN_DATE" IS '가입날짜';
--------------------------------------------------------
--  DDL for Table POINT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."POINT" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"POINT" NUMBER DEFAULT 0, 
	"WITHDRAW" NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."POINT"."LOGIN_ID" IS '외래키/소유자';
   COMMENT ON COLUMN "SCOTT"."POINT"."POINT" IS '잔여포인트';
   COMMENT ON COLUMN "SCOTT"."POINT"."WITHDRAW" IS '출금대기';
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "SCOTT"."POST" 
   (	"BOARD_NO" NUMBER(20,0), 
	"POST_NO" NUMBER(20,0), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"ANSWER" VARCHAR2(1000 BYTE), 
	"STATUS" NUMBER(20,0) DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."POST"."BOARD_NO" IS '외래키/게시판번호(공지/문의)';
   COMMENT ON COLUMN "SCOTT"."POST"."POST_NO" IS '외래키/게시글번호';
   COMMENT ON COLUMN "SCOTT"."POST"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "SCOTT"."POST"."ANSWER" IS '답변내용';
   COMMENT ON COLUMN "SCOTT"."POST"."STATUS" IS '처리상태';
--------------------------------------------------------
--  DDL for Table SHOPPING_HISTORY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."SHOPPING_HISTORY" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"REGISTER_NO" NUMBER, 
	"HISTORY_DATE" DATE DEFAULT SYSDATE, 
	"TYPE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."SHOPPING_HISTORY"."LOGIN_ID" IS '외래키/아이디';
   COMMENT ON COLUMN "SCOTT"."SHOPPING_HISTORY"."REGISTER_NO" IS '외래키/상품번호';
   COMMENT ON COLUMN "SCOTT"."SHOPPING_HISTORY"."HISTORY_DATE" IS '기록날짜';
   COMMENT ON COLUMN "SCOTT"."SHOPPING_HISTORY"."TYPE" IS '거래유형';
--------------------------------------------------------
--  DDL for Table TRANSACTION_HISTORY
--------------------------------------------------------

  CREATE TABLE "SCOTT"."TRANSACTION_HISTORY" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"HISTORY_DATE" DATE DEFAULT SYSDATE, 
	"AMOUNT" NUMBER, 
	"TYPE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EXAMPLE" ;

   COMMENT ON COLUMN "SCOTT"."TRANSACTION_HISTORY"."LOGIN_ID" IS '외래키/소유자';
   COMMENT ON COLUMN "SCOTT"."TRANSACTION_HISTORY"."HISTORY_DATE" IS '기록날짜';
   COMMENT ON COLUMN "SCOTT"."TRANSACTION_HISTORY"."AMOUNT" IS '입금액';
   COMMENT ON COLUMN "SCOTT"."TRANSACTION_HISTORY"."TYPE" IS '거래타입';
REM INSERTING into SCOTT.BANNER_IMAGE
SET DEFINE OFF;
REM INSERTING into SCOTT.BORAD
SET DEFINE OFF;
REM INSERTING into SCOTT.CART
SET DEFINE OFF;
REM INSERTING into SCOTT.GIFTICON
SET DEFINE OFF;
REM INSERTING into SCOTT.GIFTICON_IMAGE
SET DEFINE OFF;
REM INSERTING into SCOTT.IMAGE_FILE
SET DEFINE OFF;
REM INSERTING into SCOTT.MEMBER
SET DEFINE OFF;
REM INSERTING into SCOTT.POINT
SET DEFINE OFF;
REM INSERTING into SCOTT.POST
SET DEFINE OFF;
REM INSERTING into SCOTT.SHOPPING_HISTORY
SET DEFINE OFF;
REM INSERTING into SCOTT.TRANSACTION_HISTORY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BANNER_IMAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BANNER_IMAGE_PK" ON "SCOTT"."BANNER_IMAGE" ("BANNER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index BORAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."BORAD_PK" ON "SCOTT"."BORAD" ("BOARD_NO", "POST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index GIFTICON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."GIFTICON_PK" ON "SCOTT"."GIFTICON" ("REGISTER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index GIFTICON_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."GIFTICON_UK1" ON "SCOTT"."GIFTICON" ("COUPON_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index IMAGE_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."IMAGE_FILE_PK" ON "SCOTT"."IMAGE_FILE" ("FILE_PATH", "FILE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."MEMBER_PK" ON "SCOTT"."MEMBER" ("LOGIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  Constraints for Table BANNER_IMAGE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BANNER_IMAGE" MODIFY ("BANNER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BANNER_IMAGE" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BANNER_IMAGE" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BANNER_IMAGE" ADD CONSTRAINT "BANNER_IMAGE_PK" PRIMARY KEY ("BANNER_NO")
  USING INDEX "SCOTT"."BANNER_IMAGE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BORAD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BORAD" MODIFY ("BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BORAD" MODIFY ("POST_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BORAD" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BORAD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BORAD" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BORAD" MODIFY ("MODIFY_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."BORAD" ADD CONSTRAINT "BORAD_PK" PRIMARY KEY ("BOARD_NO", "POST_NO")
  USING INDEX "SCOTT"."BORAD_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CART" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."CART" MODIFY ("REGISTER_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GIFTICON
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("REGISTER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("BRAND_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("BRAND_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("COUPON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("COUPON_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("PURCHASE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("SALE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON" ADD CONSTRAINT "GIFTICON_PK" PRIMARY KEY ("REGISTER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "EXAMPLE"  ENABLE;
  ALTER TABLE "SCOTT"."GIFTICON" ADD CONSTRAINT "GIFTICON_UK1" UNIQUE ("COUPON_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "EXAMPLE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GIFTICON_IMAGE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GIFTICON_IMAGE" MODIFY ("REGISTER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON_IMAGE" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."GIFTICON_IMAGE" MODIFY ("FILE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMAGE_FILE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."IMAGE_FILE" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."IMAGE_FILE" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."IMAGE_FILE" ADD CONSTRAINT "IMAGE_FILE_PK" PRIMARY KEY ("FILE_PATH", "FILE_NAME")
  USING INDEX "SCOTT"."IMAGE_FILE_PK"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("MEMBER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("LOGIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "EXAMPLE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POINT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POINT" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POINT" MODIFY ("POINT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POINT" MODIFY ("WITHDRAW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POST" MODIFY ("BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POST" MODIFY ("POST_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."POST" MODIFY ("CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SHOPPING_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" MODIFY ("REGISTER_NO" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" MODIFY ("HISTORY_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" MODIFY ("HISTORY_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BANNER_IMAGE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BANNER_IMAGE" ADD CONSTRAINT "BANNER_IMAGE_FK1" FOREIGN KEY ("FILE_PATH", "FILE_NAME")
	  REFERENCES "SCOTT"."IMAGE_FILE" ("FILE_PATH", "FILE_NAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BORAD
--------------------------------------------------------

  ALTER TABLE "SCOTT"."BORAD" ADD CONSTRAINT "BORAD_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SCOTT"."CART" ADD CONSTRAINT "CART_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SCOTT"."CART" ADD CONSTRAINT "CART_FK2" FOREIGN KEY ("REGISTER_NO")
	  REFERENCES "SCOTT"."GIFTICON" ("REGISTER_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GIFTICON
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GIFTICON" ADD CONSTRAINT "GIFTICON_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GIFTICON_IMAGE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."GIFTICON_IMAGE" ADD CONSTRAINT "GIFTICON_IMAGE_FK1" FOREIGN KEY ("REGISTER_NO")
	  REFERENCES "SCOTT"."GIFTICON" ("REGISTER_NO") ENABLE;
  ALTER TABLE "SCOTT"."GIFTICON_IMAGE" ADD CONSTRAINT "GIFTICON_IMAGE_FK2" FOREIGN KEY ("FILE_PATH", "FILE_NAME")
	  REFERENCES "SCOTT"."IMAGE_FILE" ("FILE_PATH", "FILE_NAME") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POINT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POINT" ADD CONSTRAINT "POINT_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "SCOTT"."POST" ADD CONSTRAINT "POST_FK1" FOREIGN KEY ("BOARD_NO", "POST_NO")
	  REFERENCES "SCOTT"."BORAD" ("BOARD_NO", "POST_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SHOPPING_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" ADD CONSTRAINT "BUYHISTORY_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ENABLE;
  ALTER TABLE "SCOTT"."SHOPPING_HISTORY" ADD CONSTRAINT "BUYHISTORY_FK2" FOREIGN KEY ("REGISTER_NO")
	  REFERENCES "SCOTT"."GIFTICON" ("REGISTER_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION_HISTORY
--------------------------------------------------------

  ALTER TABLE "SCOTT"."TRANSACTION_HISTORY" ADD CONSTRAINT "DISPOSITHISTORY_FK1" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "SCOTT"."MEMBER" ("LOGIN_ID") ENABLE;
