--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-09-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER_TB
--------------------------------------------------------

  CREATE TABLE "SCOTT"."MEMBER_TB" 
   (	"LOGIN_ID" VARCHAR2(30 BYTE), 
	"LOGIN_PW" VARCHAR2(30 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
REM INSERTING into SCOTT.MEMBER_TB
SET DEFINE OFF;
Insert into SCOTT.MEMBER_TB (LOGIN_ID,LOGIN_PW,NAME,NICKNAME) values ('asdf','1234','이름1','닉네임1');
Insert into SCOTT.MEMBER_TB (LOGIN_ID,LOGIN_PW,NAME,NICKNAME) values ('qwer','11234','이름2','닉네임2');
Insert into SCOTT.MEMBER_TB (LOGIN_ID,LOGIN_PW,NAME,NICKNAME) values ('zzzq','112233','이름3','닉네임3');
Insert into SCOTT.MEMBER_TB (LOGIN_ID,LOGIN_PW,NAME,NICKNAME) values ('testid','123123','이의성','테스트');
Insert into SCOTT.MEMBER_TB (LOGIN_ID,LOGIN_PW,NAME,NICKNAME) values ('testid123','qlqjs12','가입좀','할게요');
Insert into SCOTT.MEMBER_TB (LOGIN_ID,LOGIN_PW,NAME,NICKNAME) values ('afsd3','sadf','123','gas');
Insert into SCOTT.MEMBER_TB (LOGIN_ID,LOGIN_PW,NAME,NICKNAME) values ('gasdg','asdf','dsf','sdf');
--------------------------------------------------------
--  DDL for Index MEMBER_TB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."MEMBER_TB_PK" ON "SCOTT"."MEMBER_TB" ("LOGIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_TB
--------------------------------------------------------

  ALTER TABLE "SCOTT"."MEMBER_TB" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."MEMBER_TB" ADD CONSTRAINT "MEMBER_TB_PK" PRIMARY KEY ("LOGIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE"  ENABLE;
